### ISSUE TITLE
在element-ui table下，第一页数据没有显示loading效果

### ISSUE THREAD

**Issue by wellfrog16** [PeachScript/vue-infinite-loading#265]
在element-ui table下，第一页数据没有显示loading效果。
效果参看官网示例

[https://peachscript.github.io/vue-infinite-loading/zh/guide/use-with-el-table.html](url)

右侧数据加载时，直接从“暂无数据”到显示数据，并没有出现loading

**Comment by PeachScript** [comment]
这是因为 ElementUI 的 Table 组件在数据源为空时会用『暂无数据』替代所有表格内容，包括 `append` 插槽的内容，这个问题应该提给 ElementUI，也许在 API 设计上另有考虑。

作为临时方案，可以选择用 CSS 手动隐藏 Table 空数据提示，在真的没有数据时再切换 CSS 将空数据提示展示出来：

``` css
.init-load ..el-table__empty-block {
  display: none;
}
```
